apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    app: kube-apiserver
  sessionAffinity: None
  type: LoadBalancer
